name: diet_app
description: "Aplikasi Diet Personal untuk Android"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  
  # Firebase Dependencies
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  
  # State Management
  provider: ^6.1.1
  
  # Utils & Helpers
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  
  # Image & Camera
  image_picker: ^1.0.4
  
  # Charts untuk progress tracking
  fl_chart: ^0.65.0
  
  # HTTP requests untuk API makanan
  http: ^1.1.0
  
  # Date picker
  table_calendar: ^3.0.9
  
  # Loading indicators
  flutter_spinkit: ^5.2.0

  # Path package untuk file path operations - FIXED: Added missing dependency
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets untuk gambar dan icon
  assets:
    - assets/images/
    - assets/icons/

  # Custom fonts (opsional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700