name: shihhati
description: "Aplikasi Diet Personal untuk Android"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  
  provider: ^6.1.1
  
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  
  image_picker: ^1.0.4
  permission_handler: ^11.3.1
  
  fl_chart: ^0.65.0
  
  http: ^1.1.0
  
  table_calendar: ^3.0.9
  
  flutter_spinkit: ^5.2.0

  path: ^1.8.3
  path_provider: ^2.1.2

  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  
  url_launcher: ^6.2.2

  geolocator: ^9.0.2
  sensors_plus: ^4.0.2
  pedometer: ^4.0.1

  rxdart: ^0.27.7
  
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  google_sign_in: ^6.2.1

  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/google_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icons/app_logo.png"